---
url: "http://nflix-web:8000"
database: 
  host: "localhost"
  dbname: "nflix"
  user: "postgres"
  password: "qaninja"
users: 
  catManager: 
    email: "tony@stark.com"
    password: "pwd123"
  admin:
    email: "admin@nflix.com"
    password: "admin123"